name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile test
      run: g++ test/test.cpp -std=c++17 -Wall -pedantic
    - name: run test
      run: ./a.out
